version: '3.7'

services:
  web:
    build: ./tsts_site
    command: python /usr/src/tsts_site/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tsts/:/usr/src/tsts/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:

