# Generated by Django 3.0.6 on 2020-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ID правильного ответа'),
        ),
    ]
