# Generated by Django 3.0.6 on 2020-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsts', '0003_auto_20200511_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, upload_to='answer/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='question/', verbose_name='Изображение'),
        ),
    ]
