# Generated by Django 3.0.6 on 2020-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsts', '0004_auto_20200511_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='tsts.Question')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
