# Generated by Django 3.0.6 on 2020-05-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsts', '0005_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t',
            name='t_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.CreateModel(
            name='T_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsts.Question')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsts.T')),
            ],
            options={
                'verbose_name': 'Статус ответа',
                'verbose_name_plural': 'Статусы ответов ',
            },
        ),
        migrations.RemoveField(
            model_name='t',
            name='questions',
        ),
        migrations.AddField(
            model_name='t',
            name='questions',
            field=models.ManyToManyField(through='tsts.T_Result', to='tsts.Question'),
        ),
    ]
