# Generated by Django 3.0.6 on 2020-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsts', '0008_t_result_answered_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.IntegerField(default=0, verbose_name='ID правильного ответа'),
        ),
    ]
